language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t ncondes/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true ncondes/docker-react npm run test
